name: Continuous Integration
#This workflow is for running unit and e2e testings

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  ci_verification:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test Customer Service
        working-directory: ./customer
        run: | # npm ci needs lock files
          npm ci 
          npm test 

      - name: Test Products Service
        working-directory: ./products
        run: |
          npm i
          npm test

      - name: Test Shopping Service
        working-directory: ./shopping
        run: |
          npm i
          npm test