# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy on EC2

on:
  # Since, no connection is setup yet, don't automate the process and use manual dispatch
  # push:
  #   branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Customer Service
        working-directory: ./customer
        run: |
          npm ci

      - name: Create env file
        run: |
          echo APP_SECRET=${{ secrets.APP_SECRET }} >> ./customer/.env
          echo DB_URL=${{ secrets.DB_URL }} >> ./customer/.env
          echo MSG_BROKER_URL=${{ secrets.MSG_BROKER_URL }} >> ./customer/.env
          echo EXCHANGE_NAME=${{ secrets.EXCHANGE_NAME }} >> ./customer/.env
          echo PORT=8001 >> ./customer/.env
          cat ./customer/.env

      - name: run docker compose file
        run: sudo docker-compose up --scale customer=3 -d
